### ISSUE TITLE
Support .net 4.5/C# 5

### ISSUE THREAD

**Issue by omerlh** [MattCotterellNZ/IdentityServer3.Contrib.AzureKeyVaultTokenSigningService#8]
Hey
Currently the project will not compile using C# 5. Also the code is dependent on CNG which is available only from .net 4.6.
Thanks
Omer

**Comment by MattCotterellNZ** [comment]
This is a reasonable request. I'll look into getting support going for `net452` as well. I won't be supporting anything lower than this, since MS is now dropping support for it and I do not wish to allow a framework which is no longer receiving security updates, especially in such a security-critical project. See: https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

I may hold off on actually moving this forward until ASP.NET Core RC2 lands though, since the TFMs will be changing pretty dramatically when it's released.

**Comment by omerlh** [comment]
Yes, this is sound reasonable. .NET 4.5.2 is totally enough.

**Comment by MattCotterellNZ** [comment]
This has been resolved as of e4dab5b. Only added in support for IdentityServer3 as IdentityServer4 almost inherently requires a higher .NET version.

This will be further refined when the TFMs change to the new ".NET Platform" monkiers featured in RC2, but for now this should be resolved.
